version: "3"
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
  rso-customers:
    image: kknp/rso-payment:latest
    ports:
      - 8088:8088
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/payment
    depends_on:
      - postgres